apiVersion: v1
kind: Service #What kind of object you want to create
metadata: #service name that helps uniquely identify the object
  name: empms
  
#specifies pod to use
spec: 
  selector:
    app: empms
  ports:
    - port: 8086  #port at which service is internally available
      targetPort: 8086 #port of container
     # nodePort: 30000  # port at which service is externally available  range 30000- 32767 
      name: http
  type: LoadBalancer

